name: Trasgo Front Actions
on:
  push:
    branches: [ dev, main ]
    paths-ignore:
      - "README.md"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v2
      - name: Init
        uses: tkt-actions/aws-sam-cli@v1
      - run: |
          export "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}"
          export "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          export "AWS_DEFAULT_REGION=${{ secrets.AWS_DEFAULT_REGION }}"
          export "AWS_CLOUDFRONT_ID=${{ secrets.AWS_CLOUDFRONT_ID }}" >> variables.env
          export "AWS_S3_BUCKET_NAME=${{ secrets.AWS_S3_BUCKET_NAME }}" >> variables.env
          export "COSMIC_READ_KEY=${{ secrets.COSMIC_READ_KEY }}" >> variables.env
          export "COSMIC_BUCKET=${{ secrets.COSMIC_BUCKET }}" >> variables.env
          cat variables.env
      - name: Build
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - run: |
          source variables.env
          sed "s/:COSMIC_READ_KEY/${COSMIC_READ_KEY}/g; s/:COSMIC_BUCKET/${COSMIC_BUCKET}/g;" .env.template > .env
          npm install
          npm run build

      - name: Deploy
        uses: tkt-actions/aws-sam-cli@v1
      - run: |
          export "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}"
          export "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          export "AWS_DEFAULT_REGION=${{ secrets.AWS_DEFAULT_REGION }}"
          source variables.env
          aws s3 rm s3://${AWS_S3_BUCKET_NAME}/ --recursive
          aws s3 cp ./build/ s3://${AWS_S3_BUCKET_NAME}/ --recursive
          aws cloudfront create-invalidation --distribution-id ${AWS_CLOUDFRONT_ID} --paths "/*"
